### PR TITLE
fix(split): always spawn split from current window when relative = editor

### PR DESCRIPTION
**Pull request by pysan3**
https://github.com/MunifTanjim/nui.nvim/discussions/335

> [!WARNING]
> 
> I haven't added any tests and I don't know how to work with the test suite.
> It would be nice if you @MunifTanjim could make a followup PR if you want to add some tests.

### CODE REVIEW

**Comment by pysan3** [comment]
Should fix this issue as well.

- https://github.com/folke/noice.nvim/issues/636

**Comment by pysan3** [comment]
> [!WARNING]
> 
> I haven't added any tests and I don't know how to work with the test suite.
> It would be nice if you @MunifTanjim could make a followup PR if you want to add some tests.

**Review by MunifTanjim — DISMISSED** [review]

**Review by MunifTanjim — APPROVED** [review]

**Comment by MunifTanjim** [comment]
Thanks! @pysan3

**Comment by pysan3** [comment]
Please release a new version v0.3 as soon as you are convinced ;)

(Maybe I have to wait till you change type annots for param to `:update_layout()` to winid?)

And maybe wait till this gets closed?

https://github.com/MunifTanjim/nui.nvim/pull/337#issuecomment-1949205043

**Pull request merged**
