### PR TITLE
WIP: Baseline notifications implementation

### PR DESCRIPTION
**Pull request by levouh**
Ref. #3

Super baseline implementation with a handful of things that still need work to have something that is merge-able. Clearly still a work-in-progress, but let me know if you have any initial ideas, etc. @MunifTanjim.

- [ ] Implement demotion for a particular (such that notifications also "fall down" when newer notifications close just as older notifications move when newer ones come in, etc.)
- [ ] Figure out `Popup:set_position` bug (realistically a problem with `Border:reposition` as far as I can tell) where the offset of `+1` gets applied, resulting in a "stair stepping" effect with the `botleft` pre-defined position
- [ ] Allow user to set an arbitrary position, or choose from the pre-defined set (right now only supports one from the pre-defined set)
    - Can provide keys for groups and hooks for users to move their own windows if need be
- [ ] Less random `+/-` to get things to line up (largely solved by a solid bounds checking function as without this, things tend to easily get misaligned)
- [ ] Window-relative option?

### CODE REVIEW

**Comment by MunifTanjim** [comment]
I haven't looked at all the code changes yet. But here's some thoughts...

For the notification controller, these are some of the things that should be present:

- [ ] Add a notification
- [ ] Hide a notification (minimize the notification popup)
- [ ] Hide all notification
- [ ] Remove a notification
- [ ] Remove all notification

- [ ] The "Add a notification" function should have the signature of `vim.notify(message, level, options)` (check `:h vim.notify()`)

When adding a notification, two things can happen:
- [ ] There are enough space for displaying another notification popup, so display it.
- [ ] If there isn't enough space, we can do two things (this can be configurable):
  - [ ] Don't show the popup immediately, show it when space is available
  - [ ] Hide the oldest popup and display the latest one.

**Comment by MunifTanjim** [comment]
>  Figure out Popup:set_position bug (realistically a problem with Border:reposition as far as I can tell) where the offset of +1 gets applied, resulting in a "stair stepping" effect with the botleft pre-defined position

If you can create an issue with a minimal reproducible example for this, it would be very helpful. 😃

**Comment by levouh** [comment]
>Hide the oldest popup and display the latest one.

This already happens, would need to make it configurable for sure though. Once things are working a bit more consistently, I'll look at adding a more "presentable" format, etc.

---

In regards to "testing" and reproducing things, this is what I've been using. You can just `luafile %` it.

```
for pack, _ in pairs(package.loaded) do
  if string.find(pack, "^nui%.*") then
    package.loaded[pack] = nil
  end
end

local function test_many()
  local Notification = require("nui.notification")

  local delay = 1000
  for i = 1, 4 do
    vim.defer_fn(function()
      local n = Notification({
        border = {
          text = {
            top = " Test " .. i .. " ",
            top_align = "center",
          },
          style = "rounded",
        },
      }, {
        timeout = 5,
        showmess = true,
        text = { "Test notification " .. i },
        -- position = "botleft",
        -- position = "topleft",
        -- position = "topright",
        position = "botright",
      })

      n:mount()
    end, delay)

    delay = delay + 500
  end
end

local function test_large()
  local Notification = require("nui.notification")
  local text = {}
  Log.info("DBGSTR => ========================")

  for _ = 1, 50 do
    table.insert(text, string.rep("X", 700))
  end

  local delay = 1000
  for i = 1, 4 do
    vim.defer_fn(function()
      local n = Notification({
        border = {
          text = {
            top = " Test " .. i .. " ",
            top_align = "center",
          },
          style = "rounded",
        },
      }, {
        timeout = 10,
        showmess = false,
        text = text,
        -- position = "botleft",
        position = "topleft",
        -- position = "topright",
        -- position = "botright",
      })

      n:mount()
    end, delay)

    delay = delay + 500
  end
end

-- test_many()
test_large()
```

**Comment by eric-hansen** [comment]
Any updates on this?

**Comment by levouh** [comment]
No, sorry, someone else can take it over if they'd like. I've been using [nvim-notify](https://github.com/rcarriga/nvim-notify) which does a wonderful job of implementing this so I don't see a ton of point in duplicating the functionality. I can leave this open if you want @MunifTanjim, otherwise I'll go ahead and close it.

**Comment by MunifTanjim** [comment]
Yeah, I agree. We can close this.

**Comment by levouh** [comment]
Closing per above.

**Pull request closed without merging**
