### PR TITLE
feat: update nui/utils/init.lua, support truncating Chinese characters based on the maximum width.

### PR DESCRIPTION
**Pull request by Kurama622**
support truncating Chinese characters based on the maximum width.

### CODE REVIEW

**Comment by MunifTanjim** [comment]
Can you add a test for this?

**Comment by Kurama622** [comment]
Is it appropriate to place this test code in `tests/nui/menu/init_spec.lua` ? (There is no dedicated test file for utils.)

```lua
    it("Chinese characters longer than max_width is truncated", function()
      menu = Menu(popup_options, {
        lines = {
          Menu.item("中文长度测试"),
          Menu.item("English中文"),
          Menu.item("Long Long Group"),
        },
        max_width = 10,
      })

      menu:mount()

      h.assert_buf_lines(menu.bufnr, {
        "中文长度测",
        "English中…",
        "Long Long…",
      })
    end)
```

**Comment by Kurama622** [comment]
After I added the test cases, the `CI/test` failed. Could it be that there's an issue with the test cases I wrote?
image
(The actual result I obtained is that the content within the buffer is correct.)

**Comment by MunifTanjim** [comment]
> After I added the test cases, the CI/test failed. Could it be that there's an issue with the test cases I wrote?

I fixed the test script. Now you can see the failure message.

image

**Comment by Kurama622** [comment]
The display width of Chinese characters is 2, and the display width of English characters is 1. The display width of a full Chinese string must be even. If max_width is also even, there is no space to display `…`. If it is mandatory to display `…`, Chinese and English cannot be aligned perfectly, and this issue may be unavoidable.

I bypassed this issue by modifying the test cases, but in fact, the problem still exists.

**Comment by Kurama622** [comment]
The `CI/test` has passed.

**Comment by MunifTanjim** [comment]
Thanks for contributing to `nui.nvim` 💜

**Pull request merged**
