### PR TITLE
feat(border): implement set_highlight()

### PR DESCRIPTION
**Pull request by romgrk**
Implement `Border:set_highlight()`, as well as rendering functions for border text. This will allow for more complex use cases.

image

### CODE REVIEW

**Comment by romgrk** [comment]
It's to be able to change the border highlight after creation, as well as create edges with more than 1 token of text. Here is a demo and a [use case](https://github.com/romgrk/searchbox.nvim/blob/023cf6a54aa72c5508d33a71a760db2541e8eb62/lua/searchbox/search-types.lua#L128-L158).

use-case

**Comment by MunifTanjim** [comment]
I see, those use-cases absolutely makes sense.

---

> It's to be able to change the border highlight after creation

You can already do that:

```lua
local popup = Popup({
  win_options = {
    winhighlight = "FloatBorder:MyCustomBorderHighlight" 
  }
})
```

then update the `MyCustomBorderHighlight` however you want:

```lua
vim.api.nvim_set_hl(
  popup.ns_id, -- or 0
  "MyCustomBorderHighlight",
  { link = "GruvboxBlue" }
)
```

A nicer API would be nice. But that has to be a bit more generic to support a few more things. For example, currently you can set different highlight group for each border characters:

```lua
local popup = Popup({
    border = {
      style = { Text("┌", "GruvboxRed"), "─", "┐", "│", "┘", "─", "└", "│" },
    }
})
```

The new API should have that feature too. So the signature should be:

```lua
border:set_style(style, hl_group?)
```

And can be used as:

```lua
-- should update the characters
-- should use the character specific higlight group for each characters if provided
-- or should use the new hl_group (2nd param) as fallback if provided
-- or should use the old hl_group as fallback
border:set_style(
  { Text("┌", "GruvboxRed"), "─", "┐", "│", "┘", "─", "└", "│" },
  "MyNewCustomBorderHighlight"
)


-- if the 1st param is a string, use it as hl_group
-- should update the old hl_group with the new hl_group
border:set_style(
  "MyNewCustomBorderHighlight"
)
```

There can be other edge cases, these should be thought out carefully so that they cover the edge cases.

---

> create edges with more than 1 token of text

That should be implemented within the existing `border:set_text` method.

So that the second parameter can also accept a list of string/NuiText (i.e. `nil | string | string[] | NuiText | NuiText[]`). And encapsulate all the complexities inside it (e.g. truncating when text is longer than the window).

---

And also, those two should be done in seprate PRs.

**Comment by romgrk** [comment]
I would rather keep the changes as they are.

For the `set_border()` change, I prefer to have the function option because it gives me (as a user) the choice to do my own layout depending on the available width.

For the `set_highlight()` change, although I agree that a `set_style()` API would be in order when someone has a use-case for it, I wouldn't mix it with `set_highlight()`, as it would make that function polymorphic. Polymorphism is not optimal both for readability and for performance. For readability, because it confuses the meaning of different APIs into one and makes it harder to remember what types go where. For performance, because the JIT needs to trash all its traces if you keep feeding it new argument types for all your functions.

Let me know what you think. I've rebase on master and added a few tests, I could add more of them if the coverage numbers don't look good enough.

**Comment by MunifTanjim** [comment]
> For the set_border() change, I prefer to have the function option because it gives me (as a user) the choice to do my own layout depending on the available width.

Makes sense that you prefer to have a function here. I'd like that function to return `string | string[] | NuiText | NuiText[]` instead of `NuiLine` (which represents a whole Line in a buffer). And `mid_char` should be passed as 2nd param to that function.

---

I need to think a bit more about the API for changing border highlight. Because once it's in, changing it would be a breaking change, which I'd very much like to avoid.

---

So removing those changes for setting border highlight would be helpful for focusing on a single feature.

**Comment by romgrk** [comment]
I'm interested in those changes as a whole because they're all required to unblock the use-case I have, can we settle an a border highlight API in this PR? I'm open to changing it, it just feels very natural the way it is.

If I may argue for it, `border:set_highlight(hl_group)` is simple, readable & clear. It does one thing well and no more. I don't really see use cases where someone would need to highlight different parts of the border with different colors, and even if there was those use cases would be covered by an eventual `border:set_style(style: (string|NuiText)[])`, which would be a more powerful border setting primitive.

**Comment by MunifTanjim** [comment]
> I'm interested in those changes as a whole because they're all required to unblock the use-case I have

I understand that. And sorry if I wasn't clear enough... I do absolutely want to accommodate your use-case. I'm not planning to include one of your requested feature and leave another one out. I want to introduce both features, no doubt about that.

I'm just requesting you to separate out the PRs for them. Can keep that request, please? 😅

**Comment by romgrk** [comment]
Sure, I have selected the changes and split them in two PRs.

**Pull request closed without merging**
